# fly.toml file generated for social-protocols-news on 2022-09-14T17:00:08+02:00

app = "social-protocols-news"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"
  SQLITE_DATA_DIR="/data"
  LOG_LEVEL="INFO"
  CACHE_SIZE="100"
  R2_BUCKET="news-archive"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"



# flyctl volumes create data --region ewr --size 3
[[mounts]]
  source = "data2"
  destination = "/data"

# prometheus metrics
[metrics]
  port = 9091
  path = "/metrics"

