#!/usr/bin/env bash
set -Eeuo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail

sq3() (
  sqlite3 -init <(echo) "$@"
)

if [ -z ${SQLITE_DATA_DIR+x} ]; then
  echo "no SQLITE_DATA_DIR"
  exit 1
fi

mkdir -p "$SQLITE_DATA_DIR"

DB="$SQLITE_DATA_DIR/frontpage.sqlite"

rm -rf "$DB"


echo "created $DB"
