#!/usr/bin/env bash
set -Eeuo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail

sq3() (
  sqlite3 -init <(echo) "$@"
)

if [ -z ${SQLITE_DATA_DIR+x} ]; then
  echo "no SQLITE_DATA_DIR"
  exit 1
fi

mkdir -p "$SQLITE_DATA_DIR"

DB="$SQLITE_DATA_DIR/frontpage.sqlite"

rm -rf "$DB"

sq3 "$DB" 'CREATE TABLE stories(id int primary key, by text not null, title text not null, url text not null, timestamp int not null);'
sq3 "$DB" 'CREATE TABLE dataset ( id integer not null, score integer, descendants integer not null, submissionTime integer not null, sampleTime integer not null, topRank integer, newRank integer, bestRank integer, askRank integer, showRank integer);'


echo "created $DB"

